### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by adamgibbins** [sourcegraph/thyme#8] opened 2016-08-16 20:02 UTC
Attempting to generate stats I get:
```
% ./go/bin/thyme show -i thyme.json -w stats 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xbe210]

goroutine 1 [running]:
panic(0x1f4ee0, 0xc820014130)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/sourcegraph/thyme.Stats.func1(0x0, 0xc8200b3608, 0x358358)
        /Users/aeg/go/src/github.com/sourcegraph/thyme/show.go:17 +0x20
github.com/sourcegraph/thyme.NewTimeline(0xc8200aa2c0, 0x297bc0, 0xc8200aa2c0)
        /Users/aeg/go/src/github.com/sourcegraph/thyme/show.go:161 +0x61d
github.com/sourcegraph/thyme.Stats(0xc8200aa2c0, 0x0, 0x0)
        /Users/aeg/go/src/github.com/sourcegraph/thyme/show.go:17 +0x46
main.(*ShowCmd).Execute(0x355e20, 0xc82009e370, 0x0, 0x5, 0x0, 0x0)
        /Users/aeg/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:114 +0x59e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8200d0000, 0xc82000a0d0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/aeg/go/src/github.com/jessevdk/go-flags/parser.go:314 +0xa83
github.com/jessevdk/go-flags.(*Parser).Parse(0xc8200d0000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/aeg/go/src/github.com/jessevdk/go-flags/parser.go:185 +0x9b
main.main.func1(0x0, 0x0)
        /Users/aeg/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:141 +0x2f
main.main()
        /Users/aeg/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:148 +0x23
```

**Comment by asmyers** [comment] 2016-08-17 14:55
This also occurs for me.  It appears that the Window struct is nil.  If I insert a check for nil in the above spot this crops up other places as well.

**Comment by alexmoreno** [comment] 2016-08-17 19:51
Me too.

**Comment by beyang** [comment] 2016-08-18 06:44
dupe of #15

**Closed by beyang** 2016-08-18 06:44 UTC
