### ISSUE TITLE
Where is electron

### ISSUE THREAD

**Issue by jtremback** [sourcegraph/thyme#6] opened 2016-08-16 19:32 UTC
Upon trying `thyme track` for the first time (on mac), I was presented with a file explorer window that said "Where is electron?". Since I don't have Electron, I hit "Cancel", at which point Terminal froze and I had to force quit it.

**Comment by HalfVoxel** [comment] 2016-08-16 22:03
This seems to be something that is done implicitly by the applescript that is used.
In particular this line: https://github.com/sourcegraph/thyme/blob/master/darwin.go#L45

See also https://github.com/sourcegraph/thyme/issues/3

I tried to work around it by changing the applescript code to use process IDs instead of names, but I didn't manage to get it to work.

**Comment by HalfVoxel** [comment] 2016-08-17 09:49
Worth noting is that this also seems to happen for many other applications. I get it for 'mono', 'steam' (possibly this is because of the non-standard install directory when using brew cask) and 'Android Studio'. Having this screen pop up every 30 seconds unfortunately makes thyme unusable for me.

**Comment by beyang** [comment] 2016-08-18 05:05
Thanks for reporting! Closing as dupe of #32. Let's continue the discussion there.

**Closed by beyang** 2016-08-18 05:05 UTC
