### ISSUE TITLE
Where is JavaApplicationStub?

### ISSUE THREAD

**Issue by kmatt** [sourcegraph/thyme#10] opened 2016-08-16 21:37 UTC
Was presented this with a chooser dialog, and I believe its tied to a Java based app I have open called DbVisualizer - the only Java desktop I have running.

Upon choosing the .app package, thyme terminates with:

    $ thyme track -o thyme.json
    strconv.ParseInt: parsing "": invalid syntax
    2016/08/16 17:34:45 strconv.ParseInt: parsing "": invalid syntax

This error occurs with each launch of thyme with or with any Java apps currently running.

**Comment by beyang** [comment] 2016-08-18 06:37
dupe of #32

**Closed by beyang** 2016-08-18 06:37 UTC
